[[link]]
slave_map = { 1 = 1, 3 = 2 }

# TCP options
[link.tcp]
#rtu = false
host = "localhost"
port = 5001

[[link]]
slave_map = { 2 = 1, 4 = 2 }

# TCP options
[link.tcp]
timeout = 1
#rtu = false
host = "localhost"
port = 5002
